### ISSUE TITLE
OutOfMemory error

### ISSUE THREAD

**Issue by msenra** [plamentotev/xvalid#1] opened 2019-09-19 13:15 UTC
If the file to be validated is a relatively large size above 20/30 MB, the result is an exception.
I tested with 8GB of Ram.

**Comment by plamentotev** [comment] 2019-09-19 18:27
Hi, 

You can try to increase the Java heap size. For example on Windows:

```
set JAVA_OPTS=-Xmx2G
.\bin\xvalid.bat schema.xsd document.xml
```

for Mac, Linux, etc:

```
JAVA_OPTS=-Xmx2G ./bin/xvalid.bat schema.xsd document.xml
```

This will increase the heap size to 2GB. 

Would be interesting if you can share the schema and the XML file. I've tried with XML files about 100 mb large. I guess it may depend on the complexity of the XSD file, rather solely on the XML file size.

By the way I've created this tool as a helper utility for the XML course in Sofia Univerisy, but I would be glad if it can be useful in general :)

**Comment by msenra** [comment] 2019-09-20 11:41
Yes, the problem must be due to the complexity of xsd. It is a file of the Portuguese tax authority for tax reporting. 
Xsd is version 1.1 and has multiple asserts.
I can share the schema, but not xml, because it contains a lot of data that I can't disclose.

[saft1.04.zip](https://github.com/plamentotev/xvalid/files/3635690/saft1.04.zip)

**Comment by plamentotev** [comment] 2019-09-20 13:10
Ok. Thanks. I'll take a look. If you delete all the asserts does it work?

**Comment by msenra** [comment] 2019-09-22 10:42
Yes.

**Comment by msenra** [comment] 2019-09-22 10:53
I can share a demo saft file with relevant and small data. 
[saft1.04_Demo.zip](https://github.com/plamentotev/xvalid/files/3639641/saft1.04_Demo.zip)
With this file of this size, it validates.

**Comment by plamentotev** [comment] 2019-09-24 06:03
I was able to reproduce the issue.

Some context before I go into details. What this tool  does is to make it easy to use  Apache Xerces 2(http://xerces.apache.org/xerces2-j/) from the command line. Actually one of the  Apache Xerces 2 examples does XSD 1.1 validation and provides more options. Here the focus is on the simplicity to use - making it suitable for use in the XML course. The important thing to note is that xvalid actually does very little - it just configures Xerces with some sensible defaults.

Now on what I was able to gather from profiling and debugging the application. In general Xerces uses streaming APIs to validate the schema. But if there is an assert constraint to an element, Xerces builds PSVI(Post Schema Validation Infoset) of the element. The PSVI is passed to the XPath processor (PsychoPathXPathProcessor) to evaluate the test in the assert constraint. The whole process consumes quite a lot of memory.  For around 40 mb XML file I've received OutOfMemory. With 8 GB of Java heap size it works (although quite slowly).

So in conclusion it appears that the problem is caused by the way Xerces and PsychoPathXPathProcessor work and not by the way Xerces is configured by xvalid. I'm not familiar with their code base so I'm afraid I cannot help you with this. The options I can think of are:

* you can try to increase the Java heap size even further. That worked for me. I guess the actual size depends on the XML instance content as the reason for the increased memory usage appears to the be document model. 
* you can create issue in Xerces and/or PsychoPathXPathProcessor and see what is their take on that. Xerces JIRA address is https://issues.apache.org/jira/projects/XERCESJ and for PsychoPathXPathProcessor I didn't foudn any JIRA or mailing list. The only thing I know that is used in Eclipse and appears now it is part of the source editing tools.
* or you can use another tool. Have you tried Saxon-EE (http://www.saxonica.com/download/java.xml)? It is paid but there is free evaluation so you can try it first.

p.s. I'm going to update xvalid README, making it clear that this is just wrapper around Xerces and give hints how to increase the Java heap size.

**Comment by plamentotev** [comment] 2019-10-06 18:36
I'm going to close this. If you have further question do not hesitate to re-open it again.

**Closed by plamentotev** 2019-10-06 18:36 UTC
